server:
  port: 12000

alpar:33

spring:  
  application:
    name: zuul-service-alpar
  http:
    log-request-details: true
  boot:
    admin:
      client:
        enabled: true        
        url:
        - http://localhost:8093
                
zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    test:
      path: /data/**
      url: http://localhost:8080
    index:
      path: /static/**
      url: http://localhost:8092
      
security:
  oauth2:    
    resource:
      jwk:
        key-set-uri: https://integrator.flashnet.ro:9443/oauth2/jwks
      userInfoUri: https://integrator.flashnet.ro:9443/oauth2/userinfo
      token-info-uri: https://integrator.flashnet.ro:9443/oauth2/introspect
      
eureka:
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    health-check-url: '/actuator/health'
    home-page-url: '/actuator/info'
      
logging:
  level:
    root: trace 
    
    
